apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # it can be accessed in read-write mode by a single node at a time
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data # the PersistentVolume should be created on the host machine's "/mnt/data" directory.



---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-data
#   # name: mysql-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard